project:
  name: geode_finetune
  dataset_name: GeoDE
  seed: 42

paths:
  # Put your dataset on Vast.ai here.
  # Expected structure:
  # data_root/train/<region>/<class>/<image>
  # data_root/val/<region>/<class>/<image>
  # data_root/test/<region>/<class>/<image>
  data_root: D:/Project/DAP_paper/datasets/processed/GeoDE_split

  # Leave these as null if you use data_root + train/val/test folders.
  train_dir: null
  val_dir: null
  test_dir: null

  train_split: train
  val_split: val
  test_split: test

  output_dir: D:/Project/DAP_paper/outputs/finetune/convnextv2_geode

model:
  # Available keys:
  # convnextv2_base, swinv2_base, deit3_base, dinov2_vitb14, resnet50_base224, clip_vitb16_224
  key: convnextv2_base

  # Set name directly if you want another timm model.
  # Example: resnet50.a1_in1k
  name: null

  pretrained: true
  num_classes: null   # null = infer automatically from train folder
  drop_path_rate: 0.1
  data_parallel: false

transforms:
  image_size: 224
  random_resized_crop_scale: [0.7, 1.0]
  horizontal_flip_p: 0.5
  color_jitter: [0.3, 0.3, 0.3, 0.3]
  random_grayscale_p: 0.1
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]

training:
  epochs: 20
  batch_size: 32
  num_workers: 4

  optimizer: adam     # adam or adamw
  lr: 0.00003
  weight_decay: 0.0
  label_smoothing: 0.1

  scheduler: cosine   # cosine or none
  t_max: null         # null = same as epochs
  eta_min: 0.000001

  amp: true
  device: auto        # auto, cuda, cuda:0, cpu
  save_last: true
  test_after_train: true

  # Resume examples:
  # resume: /workspace/my_training_project/outputs/convnextv2_geode/last_model.pth
  resume: null
  test_only: false
