#!/usr/bin/env python3
"""
Regenerate data-driven paper assets (LaTeX tables + figures) directly from the
original JSON result files. This keeps every number in the paper traceable to
results/<dataset>/<model>/test_results.json (fine-tuned) and
results/imagenet/<dataset>_<model>.json (ImageNet-pretrained).

Outputs:
  regional_bias_paper/paper/tables/final_main_comparison_table.tex
  regional_bias_paper/paper/tables/final_best_worst_regions_table.tex
  regional_bias_paper/paper/tables/final_tradeoff_ranking_table.tex
  regional_bias_paper/paper/tables/final_paradigm_summary_table.tex
  regional_bias_paper/paper/figures/fig_tradeoff.png
  regional_bias_paper/paper/figures/fig_finetuning_delta.png
  regional_bias_paper/paper/figures/fig_region_spread.png
  regional_bias_paper/paper/figures/fig_per_region.png
  regional_bias_paper/paper/figures/fig_paradigm_disparity.png
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
PAPER = ROOT / "regional_bias_paper" / "paper"
TABLES = PAPER / "tables"
FIGURES = PAPER / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)

# Display order and labels -----------------------------------------------------
MODELS = [
    ("resnet", "ResNet50", "Convolutional Vision"),
    ("convnext", "ConvNeXt V2", "Convolutional Vision"),
    ("deit", "DeiT III", "Transformer Vision"),
    ("swin", "SwinV2", "Transformer Vision"),
    ("dino", "DINOv2", "Self-supervised Foundation"),
    ("mae", "MAE", "Self-supervised Foundation"),
    ("clip", "CLIP", "Vision-language Foundation"),
    ("siglip", "SigLIP", "Vision-language Foundation"),
]
DATASETS = [("dollarstreet", "Dollar Street"), ("geode", "GeoDE")]

PARADIGMS = [
    "Convolutional Vision",
    "Transformer Vision",
    "Self-supervised Foundation",
    "Vision-language Foundation",
]
PARADIGM_SHORT = {
    "Convolutional Vision": "Convolutional",
    "Transformer Vision": "Transformer",
    "Self-supervised Foundation": "Self-supervised",
    "Vision-language Foundation": "Vision-language",
}
PARADIGM_COLOR = {
    "Convolutional Vision": "#4C72B0",
    "Transformer Vision": "#DD8452",
    "Self-supervised Foundation": "#55A868",
    "Vision-language Foundation": "#C44E52",
}

REGION_PRETTY = {
    "af": "Africa", "am": "Americas", "as": "Asia", "eu": "Europe",
    "Africa": "Africa", "Americas": "Americas", "EastAsia": "East Asia",
    "Europe": "Europe", "SouthEastAsia": "Southeast Asia", "WestAsia": "West Asia",
}
REGION_ORDER = {
    "dollarstreet": ["af", "am", "as", "eu"],
    "geode": ["Africa", "Americas", "EastAsia", "Europe", "SouthEastAsia", "WestAsia"],
}


def load(path: Path):
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def collect():
    """Return rows: dict keyed by (dataset, model_key) with pretrained + fine-tuned metrics."""
    rows = {}
    for ds_key, ds_name in DATASETS:
        for m_key, m_name, paradigm in MODELS:
            ft = load(RESULTS / ds_key / m_key / "test_results.json")
            pre_full = load(RESULTS / "imagenet" / f"{ds_key}_{m_key}.json")
            pre = pre_full["splits"]["test"] if "splits" in pre_full else pre_full
            rows[(ds_key, m_key)] = {
                "dataset": ds_name, "dataset_key": ds_key,
                "model": m_name, "paradigm": paradigm,
                "pre_acc": pre["object_acc"] * 100,
                "ft_acc": ft["object_acc"] * 100,
                "pre_gap": pre["region_bias_gap"] * 100,
                "ft_gap": ft["region_bias_gap"] * 100,
                "pre_best": REGION_PRETTY[pre["best_region"]],
                "pre_best_acc": pre["best_region_acc"] * 100,
                "pre_worst": REGION_PRETTY[pre["worst_region"]],
                "pre_worst_acc": pre["worst_region_acc"] * 100,
                "ft_best": REGION_PRETTY[ft["best_region"]],
                "ft_best_acc": ft["best_region_acc"] * 100,
                "ft_worst": REGION_PRETTY[ft["worst_region"]],
                "ft_worst_acc": ft["worst_region_acc"] * 100,
                "ft_region": {REGION_PRETTY[k]: v * 100
                              for k, v in ft["region_object_acc"].items()},
            }
    return rows


# -----------------------------------------------------------------------------
# LaTeX tables
# -----------------------------------------------------------------------------
HEADER = "% Auto-generated by scripts/make_paper_assets.py from the original JSON files. Do not edit by hand.\n"


def write(path: Path, body: str):
    path.write_text(HEADER + body, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def tbl_main_comparison(rows):
    lines = [
        r"\begin{table}[htbp]", r"\centering", r"\small",
        r"\caption{Pretrained-vs-fine-tuned comparison for the eight models on both datasets. "
        r"Accuracy and regional bias gap are percentages; $\Delta$ columns report the "
        r"fine-tuned-minus-pretrained change.}",
        r"\label{tab:main-comparison}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{llrrrrrr}", r"\toprule",
        r"Model & Paradigm & \multicolumn{1}{c}{Pre.\ Acc} & \multicolumn{1}{c}{FT Acc} "
        r"& \multicolumn{1}{c}{$\Delta$Acc} & \multicolumn{1}{c}{Pre.\ Gap} "
        r"& \multicolumn{1}{c}{FT Gap} & \multicolumn{1}{c}{$\Delta$Gap} \\",
        r"\midrule",
    ]
    for ds_key, ds_name in DATASETS:
        lines.append(r"\multicolumn{8}{l}{\textit{" + ds_name + r"}} \\")
        for m_key, m_name, paradigm in MODELS:
            r = rows[(ds_key, m_key)]
            lines.append(
                f"\\quad {m_name} & {PARADIGM_SHORT[paradigm]} & {r['pre_acc']:.2f} & "
                f"{r['ft_acc']:.2f} & {r['ft_acc']-r['pre_acc']:.2f} & {r['pre_gap']:.2f} & "
                f"{r['ft_gap']:.2f} & {r['ft_gap']-r['pre_gap']:.2f} \\\\"
            )
        if ds_key != DATASETS[-1][0]:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}%", r"}", r"\end{table}"]
    write(TABLES / "final_main_comparison_table.tex", "\n".join(lines) + "\n")


def tbl_best_worst(rows):
    lines = [
        r"\begin{table}[htbp]", r"\centering", r"\small",
        r"\caption{Best- and worst-performing region for each model in the pretrained and "
        r"fine-tuned states. Accuracies and gaps are percentages.}",
        r"\label{tab:best-worst}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{lllrlrr}", r"\toprule",
        r"Model & State & Best region & \multicolumn{1}{c}{Best} & Worst region "
        r"& \multicolumn{1}{c}{Worst} & \multicolumn{1}{c}{Gap} \\",
        r"\midrule",
    ]
    for ds_key, ds_name in DATASETS:
        lines.append(r"\multicolumn{7}{l}{\textit{" + ds_name + r"}} \\")
        for m_key, m_name, paradigm in MODELS:
            r = rows[(ds_key, m_key)]
            lines.append(
                f"\\quad {m_name} & Pretrained & {r['pre_best']} & {r['pre_best_acc']:.2f} & "
                f"{r['pre_worst']} & {r['pre_worst_acc']:.2f} & {r['pre_gap']:.2f} \\\\"
            )
            lines.append(
                f"\\quad {m_name} & Fine-tuned & {r['ft_best']} & {r['ft_best_acc']:.2f} & "
                f"{r['ft_worst']} & {r['ft_worst_acc']:.2f} & {r['ft_gap']:.2f} \\\\"
            )
        if ds_key != DATASETS[-1][0]:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}%", r"}", r"\end{table}"]
    write(TABLES / "final_best_worst_regions_table.tex", "\n".join(lines) + "\n")


def tbl_tradeoff(rows):
    lines = [
        r"\begin{table}[htbp]", r"\centering", r"\small",
        r"\caption{Fine-tuned accuracy and regional-gap rankings within each dataset "
        r"(rank 1 = highest accuracy / smallest gap).}",
        r"\label{tab:tradeoff-ranking}",
        r"\begin{tabular}{llrrrr}", r"\toprule",
        r"Model & Paradigm & \multicolumn{1}{c}{FT Acc} & \multicolumn{1}{c}{Acc rank} "
        r"& \multicolumn{1}{c}{FT Gap} & \multicolumn{1}{c}{Gap rank} \\",
        r"\midrule",
    ]
    for ds_key, ds_name in DATASETS:
        ds_rows = [rows[(ds_key, m_key)] for m_key, _, _ in MODELS]
        acc_rank = {id(r): i + 1 for i, r in
                    enumerate(sorted(ds_rows, key=lambda x: -x["ft_acc"]))}
        gap_rank = {id(r): i + 1 for i, r in
                    enumerate(sorted(ds_rows, key=lambda x: x["ft_gap"]))}
        lines.append(r"\multicolumn{6}{l}{\textit{" + ds_name + r"}} \\")
        for r in ds_rows:
            lines.append(
                f"\\quad {r['model']} & {PARADIGM_SHORT[r['paradigm']]} & {r['ft_acc']:.2f} & "
                f"{acc_rank[id(r)]} & {r['ft_gap']:.2f} & {gap_rank[id(r)]} \\\\"
            )
        if ds_key != DATASETS[-1][0]:
            lines.append(r"\midrule")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table}"]
    write(TABLES / "final_tradeoff_ranking_table.tex", "\n".join(lines) + "\n")


def tbl_paradigm(rows):
    lines = [
        r"\begin{table}[htbp]", r"\centering", r"\small",
        r"\caption{Paradigm-level summary of fine-tuned evaluations, averaged over the two "
        r"member models and the two datasets.}",
        r"\label{tab:paradigm-summary}",
        r"\resizebox{\linewidth}{!}{%",
        r"\begin{tabular}{llrrll}", r"\toprule",
        r"Paradigm & Models & \multicolumn{1}{c}{Mean FT acc} & \multicolumn{1}{c}{Mean FT gap} "
        r"& Highest-acc model & Lowest-gap model \\",
        r"\midrule",
    ]
    for paradigm in PARADIGMS:
        members = [(m_key, m_name) for m_key, m_name, p in MODELS if p == paradigm]
        accs, gaps = [], []
        per_model_acc, per_model_gap = {}, {}
        for m_key, m_name in members:
            ma = [rows[(ds, m_key)]["ft_acc"] for ds, _ in DATASETS]
            mg = [rows[(ds, m_key)]["ft_gap"] for ds, _ in DATASETS]
            per_model_acc[m_name] = np.mean(ma)
            per_model_gap[m_name] = np.mean(mg)
            accs += ma
            gaps += mg
        best_acc = max(per_model_acc, key=per_model_acc.get)
        low_gap = min(per_model_gap, key=per_model_gap.get)
        names = ", ".join(n for _, n in members)
        lines.append(
            f"{paradigm} & {names} & {np.mean(accs):.2f} & {np.mean(gaps):.2f} & "
            f"{best_acc} & {low_gap} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}%", r"}", r"\end{table}"]
    write(TABLES / "final_paradigm_summary_table.tex", "\n".join(lines) + "\n")


# -----------------------------------------------------------------------------
# Figures
# -----------------------------------------------------------------------------
def style():
    plt.rcParams.update({
        "font.size": 11, "axes.titlesize": 12, "axes.labelsize": 11,
        "axes.spines.top": False, "axes.spines.right": False,
        "axes.grid": True, "grid.alpha": 0.25, "grid.linewidth": 0.6,
        "figure.dpi": 200, "savefig.dpi": 200, "savefig.bbox": "tight",
        "legend.frameon": False, "legend.fontsize": 9,
    })


def paradigm_legend(ax):
    handles = [plt.Line2D([0], [0], marker="o", linestyle="", color=PARADIGM_COLOR[p],
                          label=PARADIGM_SHORT[p], markersize=7) for p in PARADIGMS]
    ax.legend(handles=handles, loc="best", title="Paradigm")


def fig_tradeoff(rows):
    style()
    fig, axes = plt.subplots(1, 2, figsize=(10, 4.2))
    for ax, (ds_key, ds_name) in zip(axes, DATASETS):
        for m_key, m_name, paradigm in MODELS:
            r = rows[(ds_key, m_key)]
            ax.scatter(r["ft_acc"], r["ft_gap"], s=70, color=PARADIGM_COLOR[paradigm],
                       edgecolor="white", linewidth=0.8, zorder=3)
            ax.annotate(m_name, (r["ft_acc"], r["ft_gap"]),
                        textcoords="offset points", xytext=(5, 4), fontsize=8)
        ax.set_title(ds_name)
        ax.set_xlabel("Fine-tuned object accuracy (%)")
        ax.set_ylabel("Regional bias gap (%)")
    paradigm_legend(axes[0])
    fig.suptitle("Accuracy versus regional disparity (fine-tuned)", y=1.02, fontsize=13)
    fig.tight_layout()
    fig.savefig(FIGURES / "fig_tradeoff.png")
    plt.close(fig)
    print("wrote figures/fig_tradeoff.png")


def fig_finetuning_delta(rows):
    style()
    fig, ax = plt.subplots(figsize=(7.2, 5.0))
    markers = {"dollarstreet": "s", "geode": "o"}
    for ds_key, ds_name in DATASETS:
        for m_key, m_name, paradigm in MODELS:
            r = rows[(ds_key, m_key)]
            ax.scatter(r["ft_acc"] - r["pre_acc"], r["ft_gap"] - r["pre_gap"],
                       s=80, marker=markers[ds_key], color=PARADIGM_COLOR[paradigm],
                       edgecolor="white", linewidth=0.8, zorder=3)
    ax.axhline(0, color="0.6", linewidth=0.8)
    ax.axvline(0, color="0.6", linewidth=0.8)
    ax.set_xlabel("Change in object accuracy after fine-tuning (%)")
    ax.set_ylabel("Change in regional bias gap after fine-tuning (%)")
    ax.set_title("Fine-tuning raises accuracy and the regional gap for all 16 pairs")
    ph = [plt.Line2D([0], [0], marker="o", linestyle="", color=PARADIGM_COLOR[p],
                     label=PARADIGM_SHORT[p], markersize=7) for p in PARADIGMS]
    dh = [plt.Line2D([0], [0], marker=markers[k], linestyle="", color="0.3",
                     label=n, markersize=7) for k, n in DATASETS]
    leg1 = ax.legend(handles=ph, loc="upper right", title="Paradigm")
    ax.add_artist(leg1)
    ax.legend(handles=dh, loc="upper left", title="Dataset")
    ax.margins(x=0.12, y=0.12)
    fig.tight_layout()
    fig.savefig(FIGURES / "fig_finetuning_delta.png")
    plt.close(fig)
    print("wrote figures/fig_finetuning_delta.png")


def fig_region_spread(rows):
    style()
    fig, axes = plt.subplots(1, 2, figsize=(11, 4.6))
    for ax, (ds_key, ds_name) in zip(axes, DATASETS):
        names = [m_name for _, m_name, _ in MODELS]
        ypos = np.arange(len(MODELS))[::-1]
        for y, (m_key, m_name, paradigm) in zip(ypos, MODELS):
            r = rows[(ds_key, m_key)]
            ax.plot([r["ft_worst_acc"], r["ft_best_acc"]], [y, y],
                    color=PARADIGM_COLOR[paradigm], linewidth=3, alpha=0.5, zorder=2)
            ax.scatter(r["ft_worst_acc"], y, color=PARADIGM_COLOR[paradigm],
                       marker="|", s=140, zorder=3)
            ax.scatter(r["ft_best_acc"], y, color=PARADIGM_COLOR[paradigm],
                       marker="|", s=140, zorder=3)
            ax.scatter(r["ft_acc"], y, color=PARADIGM_COLOR[paradigm], s=55,
                       edgecolor="white", linewidth=0.8, zorder=4)
        ax.set_yticks(ypos)
        ax.set_yticklabels(names)
        ax.set_xlabel("Object accuracy (%)")
        ax.set_title(ds_name)
        ax.grid(axis="y", visible=False)
    handles = [
        plt.Line2D([0], [0], marker="o", linestyle="", color="0.3", markersize=7,
                   label="Overall accuracy"),
        plt.Line2D([0], [0], marker="|", linestyle="", color="0.3", markersize=11,
                   label="Worst / best region"),
    ]
    axes[0].legend(handles=handles, loc="lower right")
    fig.suptitle("Overall accuracy and worst-to-best regional spread (fine-tuned)",
                 y=1.02, fontsize=13)
    fig.tight_layout()
    fig.savefig(FIGURES / "fig_region_spread.png")
    plt.close(fig)
    print("wrote figures/fig_region_spread.png")


def fig_per_region(rows):
    style()
    fig, axes = plt.subplots(1, 2, figsize=(12, 4.8),
                             gridspec_kw={"width_ratios": [4, 6]})
    for ax, (ds_key, ds_name) in zip(axes, DATASETS):
        regions = [REGION_PRETTY[r] for r in REGION_ORDER[ds_key]]
        names = [m_name for _, m_name, _ in MODELS]
        mat = np.array([[rows[(ds_key, m_key)]["ft_region"][reg] for reg in regions]
                        for m_key, _, _ in MODELS])
        im = ax.imshow(mat, aspect="auto", cmap="viridis")
        ax.set_xticks(range(len(regions)))
        ax.set_xticklabels(regions, rotation=30, ha="right")
        ax.set_yticks(range(len(names)))
        ax.set_yticklabels(names)
        ax.set_title(ds_name)
        ax.grid(False)
        thr = mat.min() + 0.55 * (mat.max() - mat.min())
        for i in range(mat.shape[0]):
            for j in range(mat.shape[1]):
                ax.text(j, i, f"{mat[i, j]:.1f}", ha="center", va="center",
                        fontsize=7, color="white" if mat[i, j] < thr else "black")
        fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, label="Accuracy (%)")
    fig.suptitle("Fine-tuned per-region object accuracy", y=1.02, fontsize=13)
    fig.tight_layout()
    fig.savefig(FIGURES / "fig_per_region.png")
    plt.close(fig)
    print("wrote figures/fig_per_region.png")


def fig_paradigm_disparity(rows):
    style()
    fig, ax = plt.subplots(figsize=(7.6, 4.6))
    xs = np.arange(len(PARADIGMS))
    means = []
    for p in PARADIGMS:
        vals = [rows[(ds, m_key)]["ft_gap"]
                for m_key, _, pm in MODELS if pm == p for ds, _ in DATASETS]
        means.append(np.mean(vals))
    bars = ax.bar(xs, means, color=[PARADIGM_COLOR[p] for p in PARADIGMS],
                  alpha=0.55, zorder=2, width=0.6)
    markers = {"dollarstreet": "s", "geode": "o"}
    for x, p in zip(xs, PARADIGMS):
        for m_key, _, pm in MODELS:
            if pm != p:
                continue
            for ds_key, _ in DATASETS:
                ax.scatter(x, rows[(ds_key, m_key)]["ft_gap"], marker=markers[ds_key],
                           color=PARADIGM_COLOR[p], edgecolor="white", linewidth=0.7,
                           s=55, zorder=3)
    for b, m in zip(bars, means):
        ax.text(b.get_x() + b.get_width() / 2, m + 0.1, f"{m:.2f}",
                ha="center", va="bottom", fontsize=9)
    ax.set_xticks(xs)
    ax.set_xticklabels([PARADIGM_SHORT[p] for p in PARADIGMS])
    ax.set_ylabel("Fine-tuned regional bias gap (%)")
    ax.set_title("Mean fine-tuned regional gap by paradigm")
    dh = [plt.Line2D([0], [0], marker=markers[k], linestyle="", color="0.3",
                     label=n, markersize=7) for k, n in DATASETS]
    ax.legend(handles=dh, loc="upper right", title="Per-model points")
    fig.tight_layout()
    fig.savefig(FIGURES / "fig_paradigm_disparity.png")
    plt.close(fig)
    print("wrote figures/fig_paradigm_disparity.png")


def main():
    rows = collect()
    tbl_main_comparison(rows)
    tbl_best_worst(rows)
    tbl_tradeoff(rows)
    tbl_paradigm(rows)
    fig_tradeoff(rows)
    fig_finetuning_delta(rows)
    fig_region_spread(rows)
    fig_per_region(rows)
    fig_paradigm_disparity(rows)
    print("done")


if __name__ == "__main__":
    main()


